
DROP DATABASE IF EXISTS `aburisk` ;
CREATE DATABASE IF NOT EXISTS `aburisk` DEFAULT CHARACTER SET utf8 ;

DROP SCHEMA IF EXISTS `aburisk` ;
CREATE SCHEMA IF NOT EXISTS `aburisk` DEFAULT CHARACTER SET utf8 ;
USE `aburisk` ;